;;; es-lib-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from es-lib-buffer-local-set-key.el

(register-definition-prefixes "es-lib-buffer-local-set-key" '("es-buffer-local-"))


;;; Generated autoloads from es-lib-core-functions.el

(autoload 'es-kill-buffer-dont-ask "es-lib-core-functions" "\


(fn &optional BUFFER)" t)
(autoload 'es-find-function-bound-to "es-lib-core-functions" "\


(fn KEY-SEQUENCE)" t)
(autoload 'es-push-line "es-lib-core-functions" "\
beginning-of-line + open line." t)
(autoload 'es-jump-line "es-lib-core-functions" "\
end-of-line + newline." t)
(autoload 'es-new-empty-buffer "es-lib-core-functions" nil t)
(defvar es-highlighter-colors '("DeepPink" "cyan" "MediumPurple1" "SpringGreen1" "DarkOrange" "HotPink1" "RoyalBlue1" "OliveDrab"))
(autoload 'es-mouse-copy-symbol "es-lib-core-functions" "\


(fn EVENT)" t)
(autoload 'es-mouse-yank-replace-symbol "es-lib-core-functions" "\


(fn EVENT)" t)
(autoload 'es-c-expand-region "es-lib-core-functions" "\
A simplee version of expand-region for c-like languages.
Marks the symbol on first call, then marks the statement." t)
(autoload 'es-comment-dwim "es-lib-core-functions" "\


(fn &optional ARG)" t)
(autoload 'es-ido-like-helm "es-lib-core-functions" "\
Choose from a concatenated list of buffers and recent files.

(fn &optional THIS-MODE-ONLY)" t)
(autoload 'es-ido-like-helm "es-lib-core-functions" "\
Choose from a concatenated list of buffers and recent files.

(fn &optional THIS-MODE-ONLY)" t)
(autoload 'es-manage-unsaved-buffers "es-lib-core-functions" "\
Similar to what happends when emacs is about to quit." t)
(autoload 'es-query-replace-symbol-at-point "es-lib-core-functions" nil t)
(autoload 'es-ack-replace-symbol "es-lib-core-functions" "\
Repalace symbol at point, or region contents in multiple
files.

(fn FROM-SYMBOL-OR-STRING TO-SYMBOL-OR-STRING &key DIRECTORY AUTO-SAVE FINISH-FUNC SILENT)" t)
(autoload 'es-ack-pin-folder "es-lib-core-functions" "\
Set ack root directory for one buffer only.
Ack won't prompt for a directory name in that buffer.

(fn FOLDER)" t)
(register-definition-prefixes "es-lib-core-functions" '("es-"))


;;; Generated autoloads from es-lib-core-macros.el

(register-definition-prefixes "es-lib-core-macros" '("es-"))


;;; Generated autoloads from es-lib-lexical.el

(register-definition-prefixes "es-lib-lexical" '("es-"))


;;; Generated autoloads from es-lib-readme-generator.el

(register-definition-prefixes "es-lib-readme-generator" '("es-"))


;;; Generated autoloads from es-lib-text-navigate.el

(register-definition-prefixes "es-lib-text-navigate" '("es-"))


;;; Generated autoloads from es-lib-total-line.el

(register-definition-prefixes "es-lib-total-line" '("es-total-"))

;;; End of scraped data

(provide 'es-lib-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; es-lib-autoloads.el ends here
